---
title: "Gov 50 Final Project"
author: "Ee Jenn Lee"
description: "My final project"
output:
  distill::distill_article:
    self_contained: false
--- 



## Project thoughts
I am interested in exploring data related to the upcoming Malaysian elections. Making predictions about election outcomes would be cool, but it might also be outside my skill set. I'm particularly interested in exploring the potential effect of a recent law lowering the voting age to 18 on election outcomes, and would look at data sets from youth opinion surveys and state-level elections to explore the role of youth in Malaysian politics. as dasdsa

## Research proposal
Does voter turnout in Malaysian elections exert an effect on whether the incumbent party is able to remain in power? In this study, I plan to examine state-level data of past Malaysian elections to examine the extent to which there is a correlation between voter turnout and the party that wins. My hypothesis is that lower voter turnout benefits the incumbent party, because dissatisfaction with the administration is often expressed as voter apathy and specifically in Malaysia, supporters of the regime are incentivized to vote by rewards, financial or otherwise. My sample consists of state-level data from the 14th General Election in 2018 as well as more recent election data from [ ]. My explanatory variable is voter turnout as a percentage of the voting-age population. My outcome variable is the party that wins the local election, which will be coded discretely and numerically. A significant positive correlation (generated by a multiple regression analysis that adjusts for potential confounders) would support my hypothesis. A negligible or negative correlation would provide evidence against my hypothesis.